all: \
	frontend/css/bootstrap.min.css frontend/css/cover.css \
	frontend/JavaScript/libs/v6.13.0-dist/ol.css \
	frontend/JavaScript/libs/v6.13.0-dist/ol.js \


frontend/css/bootstrap.min.css:
	curl -o $@ https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css

frontend/css/cover.css:
	curl -o $@ https://getbootstrap.com/docs/5.1/examples/cover/cover.css

frontend/JavaScript/libs/v6.13.0-dist/ol.css:
	curl -o $@ https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.13.0/css/ol.css

frontend/JavaScript/libs/v6.13.0-dist/ol.js:
	curl -o $@ https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.13.0/build/ol.js
